// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPXtlgZJJdQzBMxnDryOxzfCRRkr7hzUk',
    appId: '1:158682838923:web:558ef3f913e8b83f66218e',
    messagingSenderId: '158682838923',
    projectId: 'ziara-e4117',
    authDomain: 'ziara-e4117.firebaseapp.com',
    storageBucket: 'ziara-e4117.appspot.com',
    measurementId: 'G-MPZVQ7SWVK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9HnNH00qTwaOfB7WX5KO_7YcS9T5a7s0',
    appId: '1:158682838923:android:37bc2715ec20ad9466218e',
    messagingSenderId: '158682838923',
    projectId: 'ziara-e4117',
    storageBucket: 'ziara-e4117.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3LBltKajFPJtzG1O5Crj0IEecOlIeoL8',
    appId: '1:158682838923:ios:5af9498616a89dff66218e',
    messagingSenderId: '158682838923',
    projectId: 'ziara-e4117',
    storageBucket: 'ziara-e4117.appspot.com',
    iosBundleId: 'com.example.ziara',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPXtlgZJJdQzBMxnDryOxzfCRRkr7hzUk',
    appId: '1:158682838923:web:423810c71b7d9c4466218e',
    messagingSenderId: '158682838923',
    projectId: 'ziara-e4117',
    authDomain: 'ziara-e4117.firebaseapp.com',
    storageBucket: 'ziara-e4117.appspot.com',
    measurementId: 'G-8RWRYCZ4Z4',
  );
}
